version: "3"
services:
  nextjs-reviews:
    image: nextjs-reviews
    container_name: reviews
    ports:
    - 3000:3000
    networks:
    - rewnet
    volumes:
    - data:/app/data

networks:
  rewnet:
    driver: bridge

volumes:
  data: