version: 1.0
services:
  app:
    image: nextjs-reviews
    container_name: reviews
    # restart: always
    ports:
    - 433:3000
    network:
    - rewnet
    volumes:
    - data: /data

networks:
  rewnet:
    driver: bridge

volumes:
  data: