version: "1"
services:
  app:
    image: nextjs-reviews
    container_name: reviews
    ports:
    - 433:3000
    networks:
    - rewnet
    volumes:
    - data: /data

networks:
  rewnet:
    driver: bridge

volumes:
  data: