version: "3"
services:
  nextjs-reviews:
    image: nextjs-reviews
    container_name: reviews
    build:
      context: .
      # target: development
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - rewnet
    volumes:
      - data:/app/data
  nginx:
    build: ./nginx
networks:
  rewnet:
    driver: bridge

volumes:
  data:
