services:
  reviews:
    image: nextjs-reviews
    container_name: reviews
    ports:
    - 433:3000
    networks:
    - rewnet
    volumes:
    - data:/app/data

networks:
  rewnet:
    driver: bridge

volumes:
  data: